
TRIVY_IMAGE: "aquasec/trivy:latest"
DOCKERFILE_PATH: "Dockerfile"
TARGET_IMAGE: "rajkavala/javapp:latest"

# Trivy severity thresholds
SEVERITY_THRESHOLD: "LOW"  # Allowed values: LOW, MEDIUM, HIGH, CRITICAL
IGNORE_UNFIXED: false       # Whether to ignore unfixed vulnerabilities

# Build status thresholds based on vulnerabilities
BUILD_ON_FAILURE: false      # Whether to fail the build on vulnerabilities
# Add more parameters as needed
