# Trivy parameters
trivy:
 TRIVY_IMAGE: "aquasec/trivy:latest"
 DOCKERFILE_PATH: "Dockerfile"
 TARGET_IMAGE: "rajkavala/javapp:latest"
 SEVERITY_THRESHOLD: "HIGH"
 IGNORE_UNFIXED: false
 severityThreshold: high
 vulnThreshold: 10
--
sonarqube:
  qualityGate:
    passCondition: "CONDITION"
    threshold: "5.0"
--
teams:
  teamA:
    notificationEnabled: true
    teamsWebhook: ${TEAM_A_TEAMS_WEBHOOK}

  teamB:
    notificationEnabled: false
    teamsWebhook: ${TEAM_B_TEAMS_WEBHOOK}
--
notificationConfig:
  teamAWebhook: ${TEAM_A_TEAMS_WEBHOOK}
--
  
