# Trivy parameters
TRIVY_IMAGE: "aquasec/trivy:latest"
DOCKERFILE_PATH: "Dockerfile"
TARGET_IMAGE: "rajkavala/javapp:latest"
SEVERITY_THRESHOLD: "HIGH"
IGNORE_UNFIXED: false
--
sonarqube:
  qualityGate:
    passCondition: "CONDITION"
    threshold: "5.0"
--
teams:
  teamA:
    notificationEnabled: ${TEAM_A_NOTIFICATION_ENABLED}
    teamsWebhook: ${TEAM_A_TEAMS_WEBHOOK}

  teamB:
    notificationEnabled: ${TEAM_B_NOTIFICATION_ENABLED}
    teamsWebhook: ${TEAM_B_TEAMS_WEBHOOK}
--
